### ISSUE TITLE
Updating menu options causes a NullReferenceException

### ISSUE THREAD

**Issue by PetruLazar** [COS-Modding/COSML#1]
Whenever a mod tries to update the value of a menu option, like a slider, a NullReferenceException is thrown.

As a more concrete example, a mod uses the "OnLoadLocal" interface to load some data from the save file. In this function, the mod tries to update the value of the slider representing the same option as the one loaded from the save file, otherwise, the slider will show the default value for that option instead of the one actually used by the mod:
![image](https://github.com/user-attachments/assets/d4d1eb20-44ba-4e3a-82ab-7f25c941a112)

The slider is created much earlier than when local data is loaded, in the "GetMenu" interface:
![image](https://github.com/user-attachments/assets/e114c27b-0724-4eb7-8d22-66f59b2417f8)

Upon closer inspection, the exception is thrown by line 305 of the "MenuUtils.UpdateOption" function, when "label.key" is evaluated, but "label" is null:
![image](https://github.com/user-attachments/assets/bef91e05-5e87-4dfa-b7fd-175ea70a4951)

This parameters seems to be null because of a bug in the lambda defined in function "ModMenu.AddModOptions", line 141:
![image](https://github.com/user-attachments/assets/58bc49a0-0f25-496c-9ba4-fcbdff8eeb0a)

This function calls "UpdateOption" first, and then calls the appropriate Update function of the option, depending on it's type. However, for the second argument, it passes all sorts of data depending on the option type, except for the label. Since this function calls the Update function with a null label, which in turn calls "UpdateOption" again, but this time, without a label set, causing the NullReferenceException.

**Comment by Dastan21** [comment]
Why would you change the value of the slider in the `OnLoadLocal` since it will be initialized with `localData.annotationLimitIndex` when creating the slider in `GetMenu`?

**Comment by PetruLazar** [comment]
The `GetMenu` is not called if you go to the menu in-game and try to change the options of the mod. In this case, the slider is initialized before local data is loaded, with the default value from `localData.annotationLimitIndex`. If a save file is loaded, `localData.annotationLimitIndex` is updated with information from the save file, but if you go into the menu to check the settings, you will still see the default value. This can cause confusion and does not allow the actual value to be checked by the player.

**Comment by Dastan21** [comment]
Fixed in v1.0.4
